version: '3'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:3000

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
